### ISSUE TITLE
Elasticsearch integraton

### ISSUE THREAD

**Issue by zetahoq** [Cymmetria/honeycomb_plugins#107]
Config file being used
`---
version: 1

services:
  simple_http:
    parameters:
      port: 80
      version: "nginx"
      threading: false

integrations:
  elasticsearch:
    parameters:
      url: "http://xxx.xx.xxx.xxx:9200" (actual IP address is redacted)
      verify: false
      username: ""
      password: ""
      index: "firewall"
` 
Command to run being used
` honeycomb -c /home/log/.config/honeycomb/honeycomb.yml -v`

Receiving the following error when attempting to use the elastisearch integration.

`DEBUG    [2018-10-29 16:46:21,242 base_service] simple_http_service.py:50 log_message: 76.21.103.242 - - [29/Oct/2018 16:46:21] "GET / HTTP/1.1" HTTPStatus.OK -
DEBUG    [2018-10-29 16:46:21,243 honeycomb.integrationmanager.tasks] tasks.py:126 send_alert_to_configured_integration: Sending alert {'id': UUID('8cf6f20e-c499-466c-8539-4ced207dafcc'), 'status': 2, 'timestamp': datetime.datetime(2018, 10, 29, 16, 46, 21, 242214), 'event_type': 'simple_http', 'event_description': 'HTTP Server Interaction', 'request': 'GET /', 'originating_ip': '76.21.103.242', 'originating_port': 62051, 'decoy_os': 'Linux'} to elasticsearch
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/log/.local/lib/python3.6/site-packages/honeycomb/integrationmanager/tasks.py", line 101, in create_integration_alert_and_call_send
    send_alert_to_configured_integration(integration_alert)
  File "/home/log/.local/lib/python3.6/site-packages/honeycomb/integrationmanager/tasks.py", line 127, in send_alert_to_configured_integration
    output_data, output_file_content = integration_actions_instance.send_event(alert_fields)
  File "/home/log/.config/honeycomb/integrations/elasticsearch/integration.py", line 26, in send_event
    response = session.post(url=url, auth=auth, json=alert_fields, verify=verify)
  File "/home/log/.local/lib/python3.6/site-packages/requests/sessions.py", line 559, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/log/.local/lib/python3.6/site-packages/requests/sessions.py", line 498, in request
    prep = self.prepare_request(req)
  File "/home/log/.local/lib/python3.6/site-packages/requests/sessions.py", line 441, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/home/log/.local/lib/python3.6/site-packages/requests/models.py", line 312, in prepare
    self.prepare_body(data, files, json)
  File "/home/log/.local/lib/python3.6/site-packages/requests/models.py", line 462, in prepare_body
    body = complexjson.dumps(json)
  File "/usr/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'UUID' is not JSON serializable
`

**Comment by dekelb** [comment]
@zetahoq please update if this issue is now fixed or you still have problems with this integration.

**Comment by zetahoq** [comment]
Sorry, missed the up date. The config file I am using remains unchanged, though new error.

`DEBUG    [2018-10-31 20:56:10,495 honeycomb.exceptions] tasks.py:127 send_alert_to_configured_integration: Error sending integration event: status code: 405, content: b'{"error":"Incorrect HTTP method for uri [/firewall] and method [POST], allowed: [DELETE, PUT, GET, HEAD]","status":405}'
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/log/.local/lib/python3.6/site-packages/honeycomb/integrationmanager/tasks.py", line 101, in create_integration_alert_and_call_send
    send_alert_to_configured_integration(integration_alert)
  File "/home/log/.local/lib/python3.6/site-packages/honeycomb/integrationmanager/tasks.py", line 127, in send_alert_to_configured_integration
    output_data, output_file_content = integration_actions_instance.send_event(alert_fields)
  File "/home/log/.config/honeycomb/integrations/elasticsearch/integration.py", line 33, in send_event
    raise IntegrationSendEventError("status code: {}, content: {}".format(response.status_code, response.content))
integrationmanager.exceptions.IntegrationSendEventError: [-] Error sending integration event: status code: 405, content: b'{"error":"Incorrect HTTP method for uri [/firewall] and method [POST], allowed: [DELETE, PUT, GET, HEAD]","status":405}'

`

**Comment by zetahoq** [comment]
NVM, the issue was between the keyboard and chair
